### ISSUE TITLE
Drag?

### ISSUE THREAD

**Issue by willwade** [AceCentre/morAce#19]
Cant remember how we should be doing a drag mouse movement.

NB https://docs.acecentre.org.uk/products/v/morace/guides/creating-your-first-task#drag

**Comment by f1andrew** [comment]
Drag can be made with next sequence:
.---.-. (hold command)
.-       (left click)
...      (send some move commands)
.---.-- (release command)

**Comment by willwade** [comment]
Is it possible to somehow do this? ( I realise I should just test this but I'm without the electronics right now)


```
.---.-. (hold command)
.- (left click)
... (send some move commands)
.---.-  **(REPEAT)**
.---.-- (release command)
```

**Comment by f1andrew** [comment]
yes, it should work too
