### ISSUE TITLE
Switch Mode - keys being sent in this mode

### ISSUE THREAD

**Issue by willwade** [AceCentre/morAce#20]
Cant get switch control mode to work for me yet - dare say its just me

But what are the keystrokes it sends out? (see https://docs.acecentre.org.uk/products/v/morace/guides/switch-control-mode-and-morse-mode - at the bottom "It sends the character SPACE for switch 1, SPACE for switch 2. ??")

**Comment by f1andrew** [comment]
Switch control mode sends next keystrokes.
Button one mode:
Button 1 - Space

Button two mode:
Button 1 - Space
Button 2 - Enter

Button three mode:
Button 1 - Space
Button 2 - Enter
Button 3 - Backspace

**Comment by willwade** [comment]
Thanks!
