### ISSUE TITLE
Both brace characters have same Morse value ('{' & '}'

### ISSUE THREAD

**Issue by rdbrown1au** [AceCentre/morAce#35]
070     ("--...", [Keycode.SEVEN]),
071     ("--..-",  [Keycode.SHIFT, Keycode.LEFT_BRACKET]),
071     ("--..-",  [Keycode.SHIFT, Keycode.RIGHT_BRACKET]),
073     ("--.--",   [Keycode.LEFT_ALT]),         #// Alt

Output from lightly processed morseCode.py. The first octal value is a numeric encoding of the Morse string. Essentially skip the most significant set bit and read of the rest of the bitstring  as the Morse.

I've been attempting to collect encodings at https://en.wikipedia.org/wiki/User:RDBrown/AAC_Morse where I'll get around to adding yours.

**Comment by willwade** [comment]
Thanks for spotting that! Fixed thanks to @f1andrew
