### ISSUE TITLE
Better Usable editing for userconfigs

### ISSUE THREAD

**Issue by willwade** [AceCentre/morAce#39]
(Not urgent - this is really just a discussion at this stage)

CircuitPy is great - but we've now got a few places we are asking people to edit files in to use MorAce

- boot.py (to turn on/off saving)
- userconfig (for a lot of the user configurable stuff)
- morsecode (the definition of the standard morsecode set)

I'm wondering what ways we could restructure this to make it easier. 

WIth the chat with @rdbrown1au  in https://github.com/AceCentre/morAce/issues/36 there is chat whether we could/should have a different morsecode-set file. And whether we should have a keymap file (and equally functions to handle that). If we did do this there is even more to edit.

Whats the options? Here's some ideas

- Have a config/ dir
- Then have a files like <us>.keymap, and <userconfig>.kconfig (I'm wondering about kconfig files - see https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/kconfig/kconfiglib.py - and docs https://docs.zephyrproject.org/latest/build/kconfig/setting.html ) - not sure what morsecode syntax should best look like. (maybe just in a seperate <morsestandard>.kconfig

or am I overcomplicating things? Happy for ideas! @f1andrew :) 

Tagging in @gavinhenderson @paulhewett here as this may have knock on effects with x80.

**Comment by f1andrew** [comment]
turn on/off files can be included in userConfig.
Morse codes definition can be moved to separate files without any other code.
Should morsecode file contain only shortcuts or definition of main characters should be included too?



> And whether we should have a keymap file (and equally functions to handle that).

Regular typing works with other languages, it's just needed to change keyboard layout in target device(phone, pc) settings.
Here keymaps can be used only for supporting sending predefined strings in other languages.

**Comment by willwade** [comment]
@rdbrown1au - do you have a list of different code sets out there at all?  There will be some difficulties with mouse - its not just a codeset its functionality that is different between all these diff morse boxes (NB: We were copying tandemaster until Jim stepped in and pointed out his technique from adap2u which I have to admit certainly seems more efficient). Having a diff functionality like that might be more of a pain to keep up to date.

I think @f1andrew  -  it should contain definition of main characters as well as shortcuts (NB: Diff languages do have small deviations from the international standard - but main reason is some people just like diff codes. https://morsecode.world/international/morse2.html - for the accented characters etc).

**Comment by willwade** [comment]
I like kconfig for lots and lots of option menus - but cant imagine how on earth we would use it for editing a morse code keyset. It would be horrible. Also - no nice visual editor on windows. So think we need to scrap that idea

**Comment by willwade** [comment]
see https://github.com/AceCentre/morAce/pull/43
