### ISSUE TITLE
One switch method of going into file writing mode

### ISSUE THREAD

**Issue by willwade** [AceCentre/morAce#40]
Right now you have to plug a switch into 1 & 3 and press both on startup. I think we need to change this so if you held down maybe switch 1 on startup it would do the same. Reason is we might have some people only ever using one switch technique. Any other way of doing this?? A morse command maybe? 

@f1andrew

**Comment by f1andrew** [comment]
Yes, it's possible to change this to using only Key 1. I will do that.

**Comment by willwade** [comment]
Thanks! Im just wondering - is it possible to switch between these modes without pulling the power lead? Like can we trigger a reset of the power via the switch press - or something else?

**Comment by f1andrew** [comment]
I will add morse code command for triggering reset.
